### ISSUE TITLE
SP2016 version of Quickstart documentation

### ISSUE THREAD

**Issue by chanm003** [aws-quickstart/quickstart-microsoft-sharepoint#21]
I was only able to find the SP2019 deployment guide:
https://docs.aws.amazon.com/quickstart/latest/sharepoint/welcome.html

Is there a SP2016 version of the deployment guide that leverages CloudFormation? 

My goal is to have a single-server dev/test SP2016 environment running in AWS supporting less than 10 users.  High-availability is not a concern, but cost is.  Thanks!

**Comment by davmayd** [comment]
When we upgraded the Quick Start to deploy SharePoint 2019 we removed the old documentation from production. I can provide you the PDF if you message me directly (davmayd@amazon.com), just keep in mind that the 2016 templates are no longer supported
