### ISSUE TITLE
Use of Microsoft Active Directory on EC2 vs. AWS Managed Microsoft AD

### ISSUE THREAD

**Issue by tceren** [aws-quickstart/quickstart-microsoft-sharepoint#42]
In this Quickstart Reference, you had implemented 2 Amazon EC2 instances serving as Microsoft Active Directory domain controllers. Since AWS recommends using AWS Managed Microsoft AD first, I was wondering why did you choose to implement AD on EC2 for this Quickstart. This could be considered as a feature request too.

**Comment by davmayd** [comment]
I've added support for AWS managed AD and committed to the `develop` branch of the repo, once it passes our automated testing pipeline it should merge into `main`

**Comment by davmayd** [comment]
Support for AWS managed AD is now in production
