### ISSUE TITLE
Wait Condition of Resources Failing

### ISSUE THREAD

**Issue by talon6** [aws-quickstart/quickstart-microsoft-sharepoint#6]
Greetings,
I have been trying to run this quickstart in multiple regions (N.Virginia, Ohio, Oregon, N.California) and have met multiple CREATE_FAILED in the stack. Sometimes it fails at SPAPP1WaitCondition sometimes at DomainController1WaitCondition. 

Does anyone know what I could try in order to have this launch successfully? 

Please let me know if I need to provide any other information.

**Comment by raafat1983** [comment]
i go this error also but in AD2 "

Embedded stack arn:aws:cloudformation:us-west-2:952658393459:stack/SharePoint-ADStack-1FLRHAGTJRSN7/5ef766a0-68c8-11e8-a778-50d5ca11b856 was not successfully created: The following resource(s) failed to create: [DomainController2WaitCondition].
--

"

**Comment by raafat1983** [comment]
please advice

**Comment by vanstoner** [comment]
I just got this failure, after about an hour of waiting - very frustrating!
```2018-12-06 23:51:50.541000+00:00: CREATE_FAILED for SharePointStack. Reason: Embedded stack arn:aws:cloudformation:eu-west-1:080768817557:stack/sharepoint-cloudformation-SharePointStack-1PNII7U85B5JN/400f9210-f9b1-11e8-befc-0645c4e54a44 was not successfully created: The following resource(s) failed to create: [SPAPP1WaitCondition].```

**Comment by virtlima** [comment]
We have recently updated AD and SQL, and made some tweaks to Sharepoint itself. Please re-test and provide feedback. Going to close at this time.
